---

- set_fact:
    nextcloud_ssl_certificate_verification_cert_path: "{{ nextcloud_ssl_config_dir_path }}/live/{{ domain_name }}/fullchain.pem"
    nextcloud_ssl_certificate_verification_cert_key_path: "{{ nextcloud_ssl_config_dir_path }}/live/{{ domain_name }}/privkey.pem"

- name: Check if SSL certificate file exists
  stat:
    path: "{{ nextcloud_ssl_certificate_verification_cert_path }}"
  register: nextcloud_ssl_certificate_verification_cert_path_stat_result

- fail:
    msg: "Failed finding a certificate file (for domain `{{ domain_name }}`) at `{{ nextcloud_ssl_certificate_verification_cert_path }}`"
  when: "not nextcloud_ssl_certificate_verification_cert_path_stat_result.stat.exists"

- name: Check if SSL certificate key file exists
  stat:
    path: "{{ nextcloud_ssl_certificate_verification_cert_key_path }}"
  register: nextcloud_ssl_certificate_verification_cert_key_path_stat_result

- fail:
    msg: "Failed finding a certificate key file (for domain `{{ domain_name }}`) at `{{ nextcloud_ssl_certificate_verification_cert_key_path }}`"
  when: "not nextcloud_ssl_certificate_verification_cert_key_path_stat_result.stat.exists"
