---

- src: geerlingguy.docker
  version: 6.0.1

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_help.git
  version: c1f40e82b4d6b072b6f0e885239322bdaaaf554f

- src: git+https://github.com/devture/com.devture.ansible.role.systemd_docker_base.git
  version: 327d2e17f5189ac2480d6012f58cf64a2b46efba

- src: git+https://github.com/devture/com.devture.ansible.role.timesync.git
  version: cb2236f314f56f46f2a5e9971465f1d08828a4a7

- src: git+https://github.com/devture/com.devture.ansible.role.vars_preserver.git
  version: 6405ac665120e321ce30a971b1b28c874db5956f

- src: git+https://github.com/devture/com.devture.ansible.role.postgres.git
  version: f8242fb32722dae62398af464f029e0c9960d645

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_runtime_messages.git
  version: f1c78d4e85e875129790c58335d0e44385683f6b
