---

- src: geerlingguy.docker
  version: 6.0.1

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_help.git
  version: c1f40e82b4d6b072b6f0e885239322bdaaaf554f

- src: git+https://github.com/devture/com.devture.ansible.role.systemd_docker_base.git
  version: 327d2e17f5189ac2480d6012f58cf64a2b46efba

- src: git+https://github.com/devture/com.devture.ansible.role.timesync.git
  version: cb2236f314f56f46f2a5e9971465f1d08828a4a7

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_state_preserver.git
  version: 0857450721d525238ca230c9e6f8f8ad3a248564

- src: git+https://github.com/devture/com.devture.ansible.role.postgres.git
  version: cc263dfe9f672df774a22a7984d736a1e21b9f93

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_runtime_messages.git
  version: f1c78d4e85e875129790c58335d0e44385683f6b
