---

- name: Fail if using unsupported SSL certificate retrieval method
  fail:
    msg: "The `nextcloud_ssl_retrieval_method` variable contains an unsupported value"
  when: "nextcloud_ssl_retrieval_method not in ['lets-encrypt', 'self-signed', 'manually-managed', 'none']"

- name: Determine domains to obtain certificates for (Nextcloud)
  set_fact:
    domains_to_obtain_certificate_for: "['{{ hostname_nextcloud }}']"

- name: Ensure SSL certificates path exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0770
    owner: "{{ nextcloud_user_username }}"
    group: "{{ nextcloud_user_username }}"
  with_items:
    - "{{ nextcloud_ssl_log_dir_path }}"
    - "{{ nextcloud_ssl_config_dir_path }}"
  when: "nextcloud_ssl_retrieval_method != 'none'"

# Method specific tasks follow

- import_tasks: tasks/ssl/setup_ssl_lets_encrypt.yml

- import_tasks: tasks/ssl/setup_ssl_self_signed.yml

- import_tasks: tasks/ssl/setup_ssl_manually_managed.yml

