---

- name: Ensure Nextcloud group is created
  group:
    name: "{{ nextcloud_user_username }}"
    gid: "{{ nextcloud_user_gid }}"
    state: present

- name: Ensure Nextcloud user is created
  user:
    name: "{{ nextcloud_user_username }}"
    uid: "{{ nextcloud_user_gid }}"
    group: "{{ nextcloud_user_username }}"
    state: present

- name: Ensure environment variables data path exists
  file:
    path: "{{ nextcloud_environment_variables_data_path }}"
    state: directory
    mode: 0700

- name: Ensure Nextcloud base path exists
  file:
    path: "{{ nextcloud_base_data_path }}"
    state: directory
    mode: 0750
    owner: "{{ nextcloud_user_username }}"
    group: "{{ nextcloud_user_username }}"
    
- name: Preserve vars.yml on the server for easily restoring if it gets lost later on
  copy:
    src: "{{ nextcloud_vars_yml_snapshotting_src }}"
    dest: "{{ nextcloud_base_data_path }}/vars.yml"
    owner: "{{ nextcloud_user_username }}"
    group: "{{ nextcloud_user_username }}"
    mode: '0660'
  when: "nextcloud_vars_yml_snapshotting_enabled|bool"    
    

- name: Ensure Nextcloud network is created in Docker
  docker_network:
    name: "{{ nextcloud_docker_network }}"
    driver: bridge
